### PR TITLE
Fix DB migration name of v7 in the CHANGELOG.md

### PR DESCRIPTION
**Pull request by texpert**
This has been spotted when migrating to Que 2.1.0

### CODE REVIEW

**Comment by texpert** [comment]
BTW, previous, v6 DB migration, was failing on the test DB, because somehow the `pg_description` table had no row associated with the `que_jobs` relname from `pg_class`, so it was trying to run all the migration from #2.

I had to fix it with a temporary hack of setting `current = 5` here.

**Review by ZimbiX — APPROVED** [review]
Ah, thanks! I have to dash off, so I'll have to consider your second comment a bit later

**Comment by ZimbiX** [comment]
Ah, it sounds like you might be affected by https://github.com/que-rb/que/issues/363?

**Comment by texpert** [comment]
> Ah, it sounds like you might be affected by #363?

Yep, after running the migration, the comment with the version has appeared - https://github.com/texpert/rails_6_rss_reader/commit/383af1e662d31fd63d895c4713fde478a9fab76c#diff-1dd5a8f580b9615769ddc19a64a98f455d9d20eb149c443f41d9d3c797d39b12R68

Still, this could be a problem for the old users migrating.

**Comment by ZimbiX** [comment]
Damn, ok. Yeah, I'm [thinking we should add something to detect this issue](https://github.com/que-rb/que/issues/363#issuecomment-1228525503).

**Pull request merged**
